# This file was generated by GoReleaser. DO NOT EDIT.
cask "autogit" do
  version "0.3.3"

  on_macos do
    on_arm do
      sha256 "0cd5980afd90711a530e9a0859ee6c4fce2573f6b48a7e8343e34ad9acedad02"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8b8499bb034edf491ec438444d3a75cc5ca882aeae5818e75c346d960d05ac00"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "0db15c2f5d7291ee8840f2b363372c3dd17c10517e6c77c233f217d1fdc79523"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "758803d2575b4aee6c61a2408e500c49aa0f4dd15a48eac6481dfbdb89dd0664"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "autogit"
  desc "Generate commit messages and ref names with an LLM"
  homepage "https://github.com/Conte777/autogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autogit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autogit"]
    end
  end

  # No zap stanza required
end
