# This file was generated by GoReleaser. DO NOT EDIT.
cask "autogit" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "d5f94fbce2f0fc96923c5da196b8484799fe69eeef81a30d5a3a0725410137c2"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "67032d1ac33a9ddec89db62703eac7a861b505707b867ecb50275dff03ba893d"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "650340b75c721f0b75826665e7b6108acf181ef3280f9e5ff52d3e2969ad3f7a"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8d306afc3c3f8b83ce10f9c971c938bba4b4da6ddb79524ee13febacd7030532"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "autogit"
  desc "Generate commit messages and ref names with an LLM"
  homepage "https://github.com/Conte777/autogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autogit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autogit"]
    end
  end

  # No zap stanza required
end
