# This file was generated by GoReleaser. DO NOT EDIT.
cask "autogit" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "ebf40551d87fc07c813e9f53f272d9d484ed2245602752a810a32e74fdbdc80a"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "842752c63fd520c380464d303443ce59efe09efdc4672981adcd309c5d6f04e4"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "1f1a8348bb4b49a24b3c1f5dfb53cab47f83eb41ea0c84720d5ecd14bdb16173"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3e9dba90344208b4d725b8665c1a653ca85c5f38b6b9a98db2bf901b11551bfd"
      url "https://github.com/Conte777/autogit/releases/download/v#{version}/autogit_#{version}_linux_amd64.tar.gz"
    end
  end

  name "autogit"
  desc "Generate commit messages and ref names with an LLM"
  homepage "https://github.com/Conte777/autogit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "autogit"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/autogit"]
    end
  end

  # No zap stanza required
end
